spring:
  ai:
    openai:
      api-key: sk-ccde7d540ae74f54a1f28c7d46ab8d02
      base-url: https://api.deepseek.com
      chat:
        api-key: sk-ccde7d540ae74f54a1f28c7d46ab8d02
        base-url: https://api.deepseek.com
        model: deepseek-v4-flash
        temperature: 0.7
      embedding:
        base-url: http://127.0.0.1:1234/v1
        api-key: sk-1234
        model: text-embedding-bge-large-zh-v1.5
logging:
  level:
    org.springframework.ai: info